version: "3.9"
services:

    nginx:
        container_name: oop
        build: ./docker/nginx
        links:
            - php
        volumes:
            - ./:/usr/share/nginx/www
        ports:
            - ${APP_PORT:-8000}:80

    php:
        container_name: php-oop
        build: ./docker/php
        volumes:
            - ./:/usr/share/nginx/www

networks:
    default:
        external: true
        name: oop
